from __future__ import annotations

import argparse
import ast
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import NamedTuple

ROOT = Path(__file__).resolve().parents[1]
CONTEXT_DIR = Path("docs/context")
REQUIRED_CONTEXT_FILES = (
    "BOOT.md",
    "PROJECT_STATE.md",
    "NEXT_ACTION.md",
    "LAST_HANDOFF.md",
    "REPO_MAP.md",
    "TASK_ROUTER.md",
    "CONTEXT_POLICY.md",
    "README.md",
)
IGNORED_PARTS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".test-tmp",
    ".venv",
    "__pycache__",
    "checkpoints",
    "data",
    "dist",
    "external",
    "outputs",
}
TEXT_CREDENTIAL_PATTERNS = (
    "kaggle.json",
    "access_token",
    "api_key",
    "private_key",
    "id_rsa",
    "id_ed25519",
)


class CacheMetadata(NamedTuple):
    generated_at: str
    commit: str


def git_sha(root: Path) -> str:
    try:
        completed = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=root,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return "unknown"
    return completed.stdout.strip()


def metadata(root: Path) -> CacheMetadata:
    return CacheMetadata(
        generated_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        commit=git_sha(root),
    )


def read_optional(path: Path) -> str:
    if not path.is_file():
        return ""
    return path.read_text(encoding="utf-8-sig")


def has_gate5_conflict_record(root: Path) -> bool:
    return (root / "docs/research/43_gate5_kaggle_cuda_smoke_results.md").is_file()


def build_boot(meta: CacheMetadata) -> str:
    return f"""# BOOT.md - Fast Start Context For Agents

Generated: {meta.generated_at}
Commit: `{meta.commit}`

## Read Order
1. `RULES.md`
2. `AGENTS.md`
3. `docs/context/BOOT.md`
4. `docs/context/PROJECT_STATE.md`
5. `docs/context/NEXT_ACTION.md`
6. `docs/context/LAST_HANDOFF.md`
7. `docs/context/TASK_ROUTER.md`

Only open `PLAYBOOK.md` for roadmap, paper, claim, gate-status, or ambiguous tasks, or when the
context cache is stale. Use `docs/context/REPO_MAP.md` before broad repo searches.

## Current Status
- Gates 1-4 passed at engineering/smoke level.
- Gate 5 passed strict Kaggle CUDA/resume artifact validation.
- Gate 6 v8 completed normal-only CUDA training and passed strict checkpoint/reload/encoding
  validation with locked-test flags false.
- Gates 7-9 completed a validation-only, non-locked, window-level pilot on one canonical Lance
  manifest.
- A separate non-locked research MVP source is ready with 36 train-normal, 14 validation-normal,
  and 22 validation-buggy episodes across all five categories.
- Gate 10 is closed.
- Locked test is closed.
- LeWM gameplay evaluation exists only as a one-buggy-episode pilot.

## Immediate Next Task
- Run the predeclared 500-update Kaggle GPU throughput/VRAM profile on the research MVP source.
- Freeze the feasible main-run schedule before any multi-seed training.

## Safety
- Non-locked-test Kaggle actions use standing Kaggle authorization after security, license,
  protocol, and package validation.
- Fingerprints are audit/idempotency records, not approval artifacts.
- Locked-test materialization or scoring requires a separate direct user command.
- No locked-test materialization or scoring.
- No data, output, checkpoint, Lance dataset, cache, `.env`, token, or `kaggle.json` commits.
- No broad LeWM superiority, SIGReg benefit, temporal localization, SOTA, or neural locked-test
  claim from the one-buggy-episode pilot.

## Required Checks
```powershell
python scripts/update_context_cache.py --refresh-boot
python scripts/validate_context_cache.py
python -m pytest
python -m ruff check .
python -m ruff format --check .
python scripts/validate_research_release.py --ci
python scripts/check_claim_registry.py
python scripts/doctor.py
pre-commit run --all-files
```

## Fast Workflow
- Start with the context files and task router.
- Open only the files named by the router plus files discovered with targeted `rg`.
- Update `docs/context/LAST_HANDOFF.md` after each task.
- Regenerate context cache before final verification.
- Treat `PLAYBOOK.md` as the long-form source of truth, not the default first read for every
  routine code edit.
"""


def build_project_state(meta: CacheMetadata, root: Path) -> str:
    return f"""# PROJECT_STATE.md

Last updated: {meta.generated_at}
Commit: `{meta.commit}`
Generated by: `scripts/update_context_cache.py`

| Gate | Status | Evidence | Missing | Next action |
|---|---|---|---|---|
| 1 | passed | baseline pipeline, tests, release tooling | none | maintain |
| 2 | passed | strict LeWM checkpoint/runtime smoke | gameplay use | maintain |
| 3 | passed | frozen TempGlitch/WOB protocols | full official action/pair certainty | maintain |
| 4 | passed | reduced real Lance loader proof | full-scale materialization | maintain |
| 5 | passed | strict v6 Kaggle CUDA/resume artifact validation | none | maintain |
| 6 | passed | v8 Kaggle CUDA normal-only training; strict reload/encoding validator passed | detection metrics | maintain frozen checkpoint |
| 7 | passed | 10,081 real frozen-checkpoint LeWM window scores on a canonical non-locked Lance manifest | broader buggy validation coverage | preserve artifacts |
| 8 | passed | frame-difference and train-normal-fitted feature-distance scores on the identical manifest | broader comparison scope | preserve artifacts |
| 9 | passed pilot | AUROC/AUPRC plus grouped-normal-P95 F1 for six LeWM aggregations and two baselines | robust multi-episode evidence and working LeWM threshold calibration | report limitations |
| 10 | closed | no locked-test materialization or scoring | frozen decision and separate direct user command | keep closed |

## Current Safe Claims
- Checkpoint-level LeWM integration feasibility.
- Reduced real-data conversion and loader compatibility.
- Local CPU forward/backward/resume smoke evidence.
- Gate 5 Kaggle CUDA smoke/resume artifact validation passed.
- Gate 6 normal-only source audit and Lance loader evidence.
- Gate 6 bounded normal-only gameplay training engineering on Kaggle CUDA.
- Frozen Gate 6 LeWM scores and named baselines were evaluated on one identical non-locked Lance
  window manifest.
- A broader non-locked research MVP source is audited and Lance-materialized for 36/14/22
  train-normal/validation-normal/validation-buggy episodes.
- The window-level pilot contains one buggy episode; LeWM max aggregation ranked above the
  frame-difference baseline by AUROC/AUPRC, while its normal-P95 F1 was zero.

## Current Unsafe Claims
- LeWM detects gameplay glitches.
- LeWM beats baselines or is state of the art.
- SIGReg helps glitch detection.
- Temporal localization performance.
- LeWM gameplay glitch-detection performance.
- Neural locked-test result.

## Current Blocker
- The broader source has not yet completed a GPU profile or paper-grade multi-seed training.
- The prior one-buggy-episode checkpoint remains an engineering pilot and its normal-P95
  threshold produced zero recall/F1.
- Locked test remains closed.

## Current Branch Policy
- Routine safe code/docs may be committed and pushed to `main` after all checks pass.
- Non-locked-test Kaggle actions use standing authorization. Remote deletion and validator bypass
  remain prohibited; locked-test access still requires a separate direct user command.
"""


def build_next_action(meta: CacheMetadata) -> str:
    return f"""# NEXT_ACTION.md

Last updated: {meta.generated_at}
Commit: `{meta.commit}`

## Current Priority
Run the research MVP GPU profile, then freeze a feasible multi-seed training schedule.

## Success Criteria
- Preserve the Gate 7-9 pilot and the new 36/14/22 research source fingerprints.
- Measure throughput and VRAM for 500 updates without treating the profile as performance evidence.
- Freeze normal-only checkpoint selection, three seeds, and episode-level evaluation.
- Keep locked-test materialization/scoring false.

## Current Known Blocker
The broader non-locked source is ready, but GPU throughput, memory, and convergence behavior have
not been measured. The 500-update profile must complete before freezing the main-run batch size,
evaluation interval, and wall-clock budget. This does not justify opening locked test.
"""


def build_last_handoff_template(meta: CacheMetadata) -> str:
    return f"""# LAST_HANDOFF.md

Last completed task: LeWM research MVP source and runtime preparation
Commit: `{meta.commit}`
Date: {meta.generated_at}

## What Changed
- Audited and materialized the broader non-locked research source.
- Added research runtime controls and a paper-grade experimental protocol.

## Checks Passed
- Pending final verification for this task.

## Safety Status
- Gates 1-9 remain completed through a limited non-locked window-level pilot.
- Research MVP source preparation is complete; GPU profile is pending.
- No locked-test access.
- No data/output/checkpoint/credential commit intended.

## Gate Status After Task
- Gates 1-8 passed; Gate 9 passed as a limited pilot.
- Gate 10 remains closed.
- Locked test closed.

## Open Blockers
- GPU profile, multi-seed main training, and robust episode-level calibration remain unresolved.

## Next Recommended Task
- Run the 500-update non-locked GPU profile before freezing main training.

## Files Likely Relevant Next
- `docs/context/NEXT_ACTION.md`
- `docs/research/47_gate7_lewm_surprise_scoring_results.md`
- `docs/research/48_gate8_same_manifest_baseline_comparison.md`
- `docs/research/49_gate9_minimal_ablation_results.md`
- `docs/research/50_results_claim_boundary.md`
"""


def build_context_readme(meta: CacheMetadata) -> str:
    return f"""# Context Cache

Generated: {meta.generated_at}
Commit: `{meta.commit}`

This directory is the fast-start layer for coding agents. It keeps routine tasks from re-reading
the full repository and long playbook unless the task truly needs deep context.

## Files

- `BOOT.md`: first compact boot context.
- `PROJECT_STATE.md`: current gate and claim status.
- `NEXT_ACTION.md`: exactly one priority task.
- `LAST_HANDOFF.md`: latest completed-task handoff.
- `REPO_MAP.md`: generated repository and symbol map.
- `TASK_ROUTER.md`: task type to files-to-read map.
- `CONTEXT_POLICY.md`: maintenance and token-budget rules.

Regenerate with:

```powershell
python scripts/update_context_cache.py --refresh-boot
python scripts/validate_context_cache.py
```
"""


def build_context_policy() -> str:
    return """# CONTEXT_POLICY.md

## Default Rule

Do not read the whole repo for routine tasks. Start with the fast context files, then follow
`TASK_ROUTER.md` and targeted `rg` searches.

## PLAYBOOK.md

`PLAYBOOK.md` is the long-form operating bible. Open it for roadmap, paper, claim, gate-status,
safety ambiguity, or stale-cache resolution. Do not auto-load it for every small code edit.

## Cache Maintenance

- Update `LAST_HANDOFF.md` at the end of each task.
- Run `python scripts/update_context_cache.py --refresh-boot` before final verification.
- Run `python scripts/validate_context_cache.py` before commit.
- If generated context conflicts with checked artifacts, trust the artifact and refresh context.

## Safety Visibility

Safety rules must remain visible in `BOOT.md`; reducing token use must not hide Kaggle,
locked-test, artifact, credential, or claim restrictions.

## Token Budget Target

Keep `BOOT.md` under 200 lines. Use `REPO_MAP.md` and `TASK_ROUTER.md` to select files rather
than reading broad directories.
"""


def build_task_router() -> str:
    return """# TASK_ROUTER.md

| Task type | Read first | Then inspect | Do not open by default |
|---|---|---|---|
| Gate 5 Kaggle | `BOOT.md`, `PROJECT_STATE.md`, `NEXT_ACTION.md`, `docs/workflows/kaggle_automation_policy.md` | `src/glitch_detection/lewm_kaggle.py`, `src/glitch_detection/lewm_training.py`, `scripts/prepare_lewm_kaggle_package.py`, `scripts/validate_lewm_kaggle_artifacts.py`, `tests/test_lewm_kaggle.py` | `paper/`, old roadmap drafts, `outputs/` |
| Context cache | `BOOT.md`, `CONTEXT_POLICY.md`, this file | `scripts/update_context_cache.py`, `scripts/validate_context_cache.py`, `tests/test_context_cache.py`, `scripts/doctor.py`, `scripts/validate_research_release.py` | `outputs/`, `data/`, `external/` |
| Paper writing | `BOOT.md`, claim registry, `PLAYBOOK.md` paper sections | `paper/`, `docs/research/`, `docs/workflows/paper_claim_rules.md` | `outputs/`, raw data |
| Dataset protocol | `BOOT.md`, `docs/research/40_gate3_gate4_real_dataset_protocol.md` | `src/glitch_detection/lewm_data.py`, protocol modules, related tests | `paper/`, Kaggle packages |
| Locked test | `BOOT.md`, `docs/workflows/locked_test_release.md`, `RULES.md` | locked-test gate scripts and selected decision artifacts | never materialize or score without explicit approval |
| Baseline/scorer code | `BOOT.md`, `REPO_MAP.md` | `src/glitch_detection/score_clips.py`, scorer module, matching tests | `PLAYBOOK.md` unless claims/gates change |
| Release/CI hygiene | `BOOT.md`, `CONTEXT_POLICY.md` | `scripts/validate_research_release.py`, `scripts/doctor.py`, `.pre-commit-config.yaml`, release tests | experiment outputs |
"""


def path_allowed(path: Path) -> bool:
    return not any(part in IGNORED_PARTS for part in path.parts)


def python_symbols(path: Path) -> list[str]:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8-sig"))
    except (SyntaxError, UnicodeDecodeError):
        return []
    names: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef):
            names.append(node.name)
    return names[:12]


def first_doc_line(path: Path) -> str:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8-sig"))
    except (SyntaxError, UnicodeDecodeError):
        return ""
    docstring = ast.get_docstring(tree) or ""
    return docstring.splitlines()[0] if docstring else ""


def tracked_files(root: Path) -> list[Path]:
    try:
        completed = subprocess.run(
            ["git", "ls-files"],
            cwd=root,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return [path.relative_to(root) for path in root.rglob("*") if path.is_file()]
    return [Path(line) for line in completed.stdout.splitlines() if line.strip()]


def build_repo_map(meta: CacheMetadata, root: Path) -> str:
    files = [path for path in tracked_files(root) if path_allowed(path)]
    top_level = sorted({path.parts[0] for path in files if path.parts})
    python_files = [
        path
        for path in files
        if path.suffix == ".py" and path.parts and path.parts[0] in {"src", "scripts", "tests"}
    ]
    docs = [
        path
        for path in files
        if path.suffix.lower() == ".md" and path.parts and path.parts[0] in {"docs", "paper"}
    ][:80]
    lines = [
        "# REPO_MAP.md",
        "",
        f"Generated: {meta.generated_at}",
        f"Commit: `{meta.commit}`",
        "Generator: `scripts/update_context_cache.py`",
        "",
        "## Top-Level Map",
        "| Path | Purpose |",
        "|---|---|",
    ]
    purpose = {
        "src": "Reusable pipeline and model integration code.",
        "scripts": "Auditable command-line entry points.",
        "tests": "Fast default-environment tests.",
        "docs": "Research evidence, workflows, context cache, and roadmap.",
        "configs": "Experiment and runtime configuration.",
        "kaggle": "Validation-only launch packages.",
        "paper": "Cautious manuscript scaffold and generated tables.",
        "requirements": "Optional runtime requirement pins.",
    }
    for name in top_level:
        if name.startswith("."):
            continue
        lines.append(f"| `{name}/` | {purpose.get(name, 'Tracked repository path.')} |")
    lines.extend(["", "## Python Modules", "| File | Symbols | Purpose |", "|---|---|---|"])
    for path in python_files:
        if path.parts[0] == "scripts" or path.parts[0] == "src":
            symbols = ", ".join(python_symbols(root / path)) or "-"
            doc = first_doc_line(root / path) or "Python module."
            lines.append(f"| `{path.as_posix()}` | {symbols} | {doc} |")
    lines.extend(["", "## Scripts", "| Script | Purpose | Related gate |", "|---|---|---|"])
    for path in sorted(path for path in files if path.parts[:1] == ("scripts",))[:80]:
        if path.suffix == ".py":
            doc = first_doc_line(root / path) or "CLI/helper script."
            gate = "Gate 5" if "lewm" in path.name or "kaggle" in path.name else "general"
            lines.append(f"| `{path.as_posix()}` | {doc} | {gate} |")
    lines.extend(["", "## Tests", "| Test | Coverage |", "|---|---|"])
    for path in sorted(path for path in files if path.parts[:1] == ("tests",))[:120]:
        if path.suffix == ".py":
            lines.append(f"| `{path.as_posix()}` | {path.stem.removeprefix('test_')} |")
    lines.extend(["", "## Docs", "| Doc | Purpose |", "|---|---|"])
    for path in docs:
        lines.append(f"| `{path.as_posix()}` | {path.stem.replace('_', ' ')} |")
    lines.append("")
    return "\n".join(lines)


def expected_files(root: Path, *, refresh_boot: bool) -> dict[str, str]:
    meta = metadata(root)
    return {
        "PROJECT_STATE.md": build_project_state(meta, root),
        "NEXT_ACTION.md": build_next_action(meta),
        "REPO_MAP.md": build_repo_map(meta, root),
        "TASK_ROUTER.md": build_task_router(),
        "CONTEXT_POLICY.md": build_context_policy(),
        "README.md": build_context_readme(meta),
        **({"BOOT.md": build_boot(meta)} if refresh_boot else {}),
    }


def write_if_changed(path: Path, content: str) -> bool:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def update_context_cache(root: Path, *, refresh_boot: bool = False) -> list[Path]:
    context_dir = root / CONTEXT_DIR
    context_dir.mkdir(parents=True, exist_ok=True)
    changed: list[Path] = []
    for name, content in expected_files(root, refresh_boot=refresh_boot).items():
        path = context_dir / name
        if write_if_changed(path, content):
            changed.append(path)
    boot = context_dir / "BOOT.md"
    if not boot.is_file():
        if write_if_changed(boot, build_boot(metadata(root))):
            changed.append(boot)
    handoff = context_dir / "LAST_HANDOFF.md"
    if not handoff.is_file():
        if write_if_changed(handoff, build_last_handoff_template(metadata(root))):
            changed.append(handoff)
    return changed


def context_validation_errors(root: Path) -> list[str]:
    context_dir = root / CONTEXT_DIR
    errors: list[str] = []
    for name in REQUIRED_CONTEXT_FILES:
        if not (context_dir / name).is_file():
            errors.append(f"missing context file: {(CONTEXT_DIR / name).as_posix()}")
    if errors:
        return errors

    boot_lines = (context_dir / "BOOT.md").read_text(encoding="utf-8-sig").splitlines()
    if len(boot_lines) > 200:
        errors.append(f"BOOT.md exceeds 200 lines: {len(boot_lines)}")

    project_state = (context_dir / "PROJECT_STATE.md").read_text(encoding="utf-8-sig")
    if "| Gate | Status | Evidence | Missing | Next action |" not in project_state:
        errors.append("PROJECT_STATE.md missing gate table")
    if "| 5 | passed |" not in project_state:
        errors.append("PROJECT_STATE.md must record Gate 5 passed")

    next_action = (context_dir / "NEXT_ACTION.md").read_text(encoding="utf-8-sig")
    if next_action.count("## Current Priority") != 1:
        errors.append("NEXT_ACTION.md must contain exactly one Current Priority section")

    handoff = (context_dir / "LAST_HANDOFF.md").read_text(encoding="utf-8-sig")
    for heading in (
        "Last completed task:",
        "Commit:",
        "Date:",
        "## What Changed",
        "## Checks Passed",
        "## Safety Status",
        "## Gate Status After Task",
        "## Open Blockers",
        "## Next Recommended Task",
        "## Files Likely Relevant Next",
    ):
        if heading not in handoff:
            errors.append(f"LAST_HANDOFF.md missing heading: {heading}")

    repo_map = (context_dir / "REPO_MAP.md").read_text(encoding="utf-8-sig")
    for heading in ("## Python Modules", "## Scripts", "## Tests"):
        if heading not in repo_map:
            errors.append(f"REPO_MAP.md missing section: {heading}")

    task_router = (context_dir / "TASK_ROUTER.md").read_text(encoding="utf-8-sig")
    if "Gate 5 Kaggle" not in task_router:
        errors.append("TASK_ROUTER.md missing Gate 5 row")

    for path in REQUIRED_CONTEXT_FILES:
        text = (context_dir / path).read_text(encoding="utf-8-sig").lower()
        if any(pattern in text for pattern in TEXT_CREDENTIAL_PATTERNS):
            if path in {"BOOT.md", "CONTEXT_POLICY.md"} and "kaggle.json" in text:
                continue
            errors.append(f"{path} contains credential-looking text")
        if "outputs/" in text and path in {"LAST_HANDOFF.md", "REPO_MAP.md"}:
            errors.append(f"{path} references forbidden output paths as context")
    return errors


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate or validate fast agent context cache.")
    parser.add_argument("--refresh-boot", action="store_true", help="Regenerate BOOT.md.")
    parser.add_argument("--check", action="store_true", help="Validate without modifying files.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if not args.check:
        changed = update_context_cache(ROOT, refresh_boot=args.refresh_boot)
        if changed:
            for path in changed:
                print(f"updated: {path.relative_to(ROOT).as_posix()}")
        else:
            print("Context cache already current.")
    errors = context_validation_errors(ROOT)
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    print("Context cache validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
